import {
  asContentItemId, asCustomFieldId, asCustomTableId, asMailConfirmationId, asMailFormId,
  asMailNotificationId, asMailSubmissionId, asSiteId, DomainError,
  type ContentItemId, type MailConfirmationId, type MailFormId, type MailNotificationId,
  type MailSubmissionId, type SiteId, type WorkspaceId,
} from "@baser-edge/core-types";
import type {
  MailConfirmationSession, MailFormDefinition, MailFormFieldPolicy, MailFormStore, MailNotification,
  MailSubmission, MailSubmissionPayload, MailSubmissionView,
} from "@baser-edge/mail-form-kernel";
import type { D1DatabaseLike, D1PreparedStatementLike } from "./index.js";

export class D1MailFormStore implements MailFormStore {
  readonly #db:D1DatabaseLike; constructor(db:D1DatabaseLike){this.#db=db;}
  async createForm(form:MailFormDefinition,policies:MailFormFieldPolicy[]):Promise<void>{
    const statements:D1PreparedStatementLike[]=[this.#db.prepare("INSERT INTO mail_forms(id,workspace_id,site_id,content_item_id,table_id,recipient_emails_json,sender_address,subject_template,auto_reply_enabled,auto_reply_email_field_key,auto_reply_subject,confirmation_ttl_seconds,retention_days,turnstile_required,state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(form.id,form.workspaceId,form.siteId,form.contentItemId,form.tableId,JSON.stringify(form.recipientEmails),form.senderAddress,form.subjectTemplate,form.autoReplyEnabled?1:0,form.autoReplyEmailFieldKey,form.autoReplySubject,form.confirmationTtlSeconds,form.retentionDays,form.turnstileRequired?1:0,form.state,form.createdAt,form.updatedAt)];
    for(const p of policies)statements.push(this.#db.prepare("INSERT INTO mail_form_field_policies(mail_form_id,field_id,privacy_class,include_owner_notification,include_auto_reply,created_at) VALUES(?,?,?,?,?,?)").bind(p.mailFormId,p.fieldId,p.privacyClass,p.includeInOwnerNotification?1:0,p.includeInAutoReply?1:0,p.createdAt));
    try{await this.#db.batch(statements);}catch(error){throw translate(error);}
  }
  async getForm(id:MailFormId):Promise<MailFormDefinition|null>{const row=await this.#db.prepare("SELECT * FROM mail_forms WHERE id=?").bind(id).first<FormRow>();return row?mapForm(row):null;}
  async getFormByContentItem(id:ContentItemId):Promise<MailFormDefinition|null>{const row=await this.#db.prepare("SELECT * FROM mail_forms WHERE content_item_id=?").bind(id).first<FormRow>();return row?mapForm(row):null;}
  async listForms(siteId:SiteId):Promise<MailFormDefinition[]>{return(await this.#db.prepare("SELECT * FROM mail_forms WHERE site_id=? ORDER BY created_at").bind(siteId).all<FormRow>()).results.map(mapForm);}
  async listFieldPolicies(id:MailFormId):Promise<MailFormFieldPolicy[]>{return(await this.#db.prepare("SELECT * FROM mail_form_field_policies WHERE mail_form_id=?").bind(id).all<PolicyRow>()).results.map(mapPolicy);}
  async createConfirmation(s:MailConfirmationSession):Promise<void>{await this.#db.prepare("INSERT INTO mail_confirmation_sessions(id,mail_form_id,schema_version,values_json,values_hash,client_fingerprint_hash,expires_at,used_at,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(s.id,s.mailFormId,s.schemaVersion,JSON.stringify(s.values),s.valuesHash,s.clientFingerprintHash,s.expiresAt,s.usedAt,s.createdAt).run();}
  async getConfirmation(id:MailConfirmationId):Promise<MailConfirmationSession|null>{const row=await this.#db.prepare("SELECT * FROM mail_confirmation_sessions WHERE id=?").bind(id).first<ConfirmationRow>();return row?mapConfirmation(row):null;}
  async acceptSubmission(input:{confirmationId:MailConfirmationId;submission:MailSubmission;payload:MailSubmissionPayload;notifications:MailNotification[];now:number}):Promise<MailSubmission>{
    const s=input.submission;const statements:D1PreparedStatementLike[]=[this.#db.prepare("INSERT INTO mail_submissions(id,mail_form_id,confirmation_id,schema_version,payload_hash,payload_state,client_fingerprint_hash,received_at,purge_at,state) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(s.id,s.mailFormId,s.confirmationId,s.schemaVersion,s.payloadHash,s.payloadState,s.clientFingerprintHash,s.receivedAt,s.purgeAt,s.state),this.#db.prepare("INSERT INTO mail_submission_payloads(submission_id,values_json,created_at) VALUES(?,?,?)").bind(input.payload.submissionId,JSON.stringify(input.payload.values),input.payload.createdAt)];
    for(const n of input.notifications)statements.push(this.#db.prepare("INSERT INTO mail_notification_outbox(id,submission_id,notification_kind,recipient,subject,state,attempts,available_at,sent_at,last_error) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(n.id,n.submissionId,n.kind,n.recipient,n.subject,n.state,n.attempts,n.availableAt,n.sentAt,n.lastError));
    try{await this.#db.batch(statements);}catch(error){throw translate(error);}return s;
  }
  async getSubmission(id:MailSubmissionId):Promise<MailSubmissionView|null>{const row=await this.#db.prepare("SELECT s.*,p.values_json FROM mail_submissions s LEFT JOIN mail_submission_payloads p ON p.submission_id=s.id WHERE s.id=?").bind(id).first<SubmissionRow>();return row?mapSubmissionView(row):null;}
  async listSubmissions(id:MailFormId):Promise<MailSubmissionView[]>{return(await this.#db.prepare("SELECT s.*,p.values_json FROM mail_submissions s LEFT JOIN mail_submission_payloads p ON p.submission_id=s.id WHERE s.mail_form_id=? ORDER BY s.received_at DESC").bind(id).all<SubmissionRow>()).results.map(mapSubmissionView);}
  async purgeSubmission(id:MailSubmissionId,now:number):Promise<MailSubmission>{try{await this.#db.batch([this.#db.prepare("DELETE FROM mail_submission_payloads WHERE submission_id=?").bind(id),this.#db.prepare("UPDATE mail_submissions SET payload_state='purged' WHERE id=?").bind(id)]);}catch(error){throw translate(error);}const view=await this.getSubmission(id);if(!view)throw new DomainError("MAIL_SUBMISSION_NOT_FOUND","Submission not found",404);return view.submission;}
  async listPendingNotifications(limit:number,now:number):Promise<MailNotification[]>{return(await this.#db.prepare("SELECT * FROM mail_notification_outbox WHERE state='pending' AND available_at<=? ORDER BY available_at LIMIT ?").bind(now,limit).all<NotificationRow>()).results.map(mapNotification);}
  async getNotification(id:MailNotificationId):Promise<MailNotification|null>{const row=await this.#db.prepare("SELECT * FROM mail_notification_outbox WHERE id=?").bind(id).first<NotificationRow>();return row?mapNotification(row):null;}
  async listNotificationsForSubmission(id:MailSubmissionId):Promise<MailNotification[]>{return(await this.#db.prepare("SELECT * FROM mail_notification_outbox WHERE submission_id=? ORDER BY id").bind(id).all<NotificationRow>()).results.map(mapNotification);}
  async updateNotification(n:MailNotification):Promise<void>{await this.#db.prepare("UPDATE mail_notification_outbox SET state=?,attempts=?,available_at=?,sent_at=?,last_error=? WHERE id=?").bind(n.state,n.attempts,n.availableAt,n.sentAt,n.lastError,n.id).run();}
  async updateSubmissionState(id:MailSubmissionId,state:MailSubmission["state"]):Promise<void>{await this.#db.prepare("UPDATE mail_submissions SET state=? WHERE id=?").bind(state,id).run();}
}

type FormRow={id:string;workspace_id:string;site_id:string;content_item_id:string;table_id:string;recipient_emails_json:string;sender_address:string;subject_template:string;auto_reply_enabled:number;auto_reply_email_field_key:string|null;auto_reply_subject:string;confirmation_ttl_seconds:number;retention_days:number;turnstile_required:number;state:MailFormDefinition["state"];created_at:number;updated_at:number};
type PolicyRow={mail_form_id:string;field_id:string;privacy_class:MailFormFieldPolicy["privacyClass"];include_owner_notification:number;include_auto_reply:number;created_at:number};
type ConfirmationRow={id:string;mail_form_id:string;schema_version:number;values_json:string;values_hash:string;client_fingerprint_hash:string;expires_at:number;used_at:number|null;created_at:number};
type SubmissionRow={id:string;mail_form_id:string;confirmation_id:string;schema_version:number;payload_hash:string;payload_state:MailSubmission["payloadState"];client_fingerprint_hash:string;received_at:number;purge_at:number;state:MailSubmission["state"];values_json:string|null};
type NotificationRow={id:string;submission_id:string;notification_kind:MailNotification["kind"];recipient:string;subject:string;state:MailNotification["state"];attempts:number;available_at:number;sent_at:number|null;last_error:string};
function mapForm(r:FormRow):MailFormDefinition{return{id:asMailFormId(r.id),workspaceId:r.workspace_id as WorkspaceId,siteId:asSiteId(r.site_id),contentItemId:asContentItemId(r.content_item_id),tableId:asCustomTableId(r.table_id),recipientEmails:JSON.parse(r.recipient_emails_json),senderAddress:r.sender_address,subjectTemplate:r.subject_template,autoReplyEnabled:Boolean(r.auto_reply_enabled),autoReplyEmailFieldKey:r.auto_reply_email_field_key,autoReplySubject:r.auto_reply_subject,confirmationTtlSeconds:r.confirmation_ttl_seconds,retentionDays:r.retention_days,turnstileRequired:Boolean(r.turnstile_required),state:r.state,createdAt:r.created_at,updatedAt:r.updated_at};}
function mapPolicy(r:PolicyRow):MailFormFieldPolicy{return{mailFormId:asMailFormId(r.mail_form_id),fieldId:asCustomFieldId(r.field_id),privacyClass:r.privacy_class,includeInOwnerNotification:Boolean(r.include_owner_notification),includeInAutoReply:Boolean(r.include_auto_reply),createdAt:r.created_at};}
function mapConfirmation(r:ConfirmationRow):MailConfirmationSession{return{id:asMailConfirmationId(r.id),mailFormId:asMailFormId(r.mail_form_id),schemaVersion:r.schema_version,values:JSON.parse(r.values_json),valuesHash:r.values_hash,clientFingerprintHash:r.client_fingerprint_hash,expiresAt:r.expires_at,usedAt:r.used_at,createdAt:r.created_at};}
function mapSubmissionView(r:SubmissionRow):MailSubmissionView{return{submission:{id:asMailSubmissionId(r.id),mailFormId:asMailFormId(r.mail_form_id),confirmationId:asMailConfirmationId(r.confirmation_id),schemaVersion:r.schema_version,payloadHash:r.payload_hash,payloadState:r.payload_state,clientFingerprintHash:r.client_fingerprint_hash,receivedAt:r.received_at,purgeAt:r.purge_at,state:r.state},values:r.values_json?JSON.parse(r.values_json):null,redacted:false};}
function mapNotification(r:NotificationRow):MailNotification{return{id:asMailNotificationId(r.id),submissionId:asMailSubmissionId(r.submission_id),kind:r.notification_kind,recipient:r.recipient,subject:r.subject,state:r.state,attempts:r.attempts,availableAt:r.available_at,sentAt:r.sent_at,lastError:r.last_error};}
function translate(error:unknown):DomainError{const m=error instanceof Error?error.message:String(error);if(m.includes("MAIL_CONFIRMATION_INVALID_OR_USED"))return new DomainError("MAIL_CONFIRMATION_USED","Confirmation is invalid, expired, or already used",409);if(m.includes("MAIL_FORM_INVALID_BINDING"))return new DomainError("MAIL_FORM_INVALID_BINDING","Mail form binding is invalid",422);return new DomainError("D1_MAIL_FORM_ERROR",m,500);}
