import {
  asMailConfirmationId, asMailFormId, asMailNotificationId, asMailSubmissionId, assertDomain, DomainError,
  newId, sha256, signCompactToken, stableStringify, systemClock, verifyCompactToken,
  type ActorContext, type Clock, type ContentNodeId, type CustomFieldId, type CustomTableId,
  type MailConfirmationId, type MailFormId, type MailSubmissionId, type SiteId,
} from "@baser-edge/core-types";
import { Capabilities } from "@baser-edge/authorization";
import { CmsService, type ContentSnapshot } from "@baser-edge/content-kernel";
import { CustomContentService, type CustomTableSchema } from "@baser-edge/custom-content-kernel";
import { createEmptyDocument, type StructuredDocument } from "@baser-edge/structured-document";
import type {
  BotVerifier, MailConfirmationSession, MailFormDefinition, MailFormFieldPolicy, MailNotification,
  MailNotificationDeliveryResult, MailSender, MailSubmission, MailSubmissionPayload, MailSubmissionView,
  PreparedMailConfirmation, PrivacyClass,
} from "./entities.js";
import type { MailFormStore } from "./store.js";
import { UnavailableBotVerifier } from "./turnstile.js";

export class MailFormService {
  readonly #store: MailFormStore; readonly #cms:CmsService; readonly #custom:CustomContentService;
  readonly #clock:Clock; readonly #signingSecret:string; readonly #privacySalt:string; readonly #bot:BotVerifier; readonly #sender:MailSender|null;
  constructor(input:{store:MailFormStore;cms:CmsService;customContent:CustomContentService;signingSecret:string;privacySalt?:string;botVerifier?:BotVerifier;sender?:MailSender;clock?:Clock}){
    this.#store=input.store;this.#cms=input.cms;this.#custom=input.customContent;this.#signingSecret=input.signingSecret;this.#privacySalt=input.privacySalt??input.signingSecret;this.#bot=input.botVerifier??new UnavailableBotVerifier();this.#sender=input.sender??null;this.#clock=input.clock??systemClock;
  }
  get store():MailFormStore{return this.#store;}

  async createMailForm(actor:ActorContext,input:{siteId:SiteId;parentId:ContentNodeId|null;slug:string;title:string;tableId:CustomTableId;recipientEmails:string[];senderAddress:string;subjectTemplate?:string;autoReplyEnabled?:boolean;autoReplyEmailFieldKey?:string|null;autoReplySubject?:string;confirmationTtlSeconds?:number;retentionDays?:number;turnstileRequired?:boolean;document?:StructuredDocument;fieldPolicies?:Array<{fieldId:CustomFieldId;privacyClass?:PrivacyClass;includeInOwnerNotification?:boolean;includeInAutoReply?:boolean}>;}):Promise<{definition:MailFormDefinition;snapshot:ContentSnapshot}> {
    const schema=await this.#custom.getTableSchema(input.tableId); const site=await this.#cms.store.getSite(input.siteId);
    assertDomain(site,"SITE_NOT_FOUND","Site not found",404);assertDomain(schema.table.workspaceId===site.workspaceId,"MAIL_TABLE_WORKSPACE_MISMATCH","Table belongs to another workspace",422);
    assertDomain(schema.table.kind==="content","MAIL_TABLE_KIND_INVALID","Mail forms require a content table",422);assertDomain(schema.fields.length>0,"MAIL_FORM_EMPTY","Attach at least one field",422);assertDomain(schema.fields.length<=100,"MAIL_FORM_TOO_MANY_FIELDS","Mail forms support at most 100 fields",422);
    for(const {definition} of schema.fields)assertDomain(!["asset","richtext"].includes(definition.type),"MAIL_FIELD_TYPE_UNSUPPORTED",`${definition.name} cannot be used in a public mail form`,422);
    const recipients=normalizeEmails(input.recipientEmails); const sender=normalizeEmail(input.senderAddress,"senderAddress");
    const subjectTemplate=normalizeSubject(input.subjectTemplate??"【{{formTitle}}】お問い合わせ","subjectTemplate");
    const autoReplySubject=normalizeSubject(input.autoReplySubject??"お問い合わせを受け付けました","autoReplySubject");
    const autoReplyKey=input.autoReplyEmailFieldKey?.trim()||null;
    if(input.autoReplyEnabled){assertDomain(autoReplyKey,"MAIL_AUTOREPLY_FIELD_REQUIRED","Auto reply requires an email field",422);const field=schema.fields.find((f)=>f.definition.key===autoReplyKey);assertDomain(field?.definition.type==="email","MAIL_AUTOREPLY_FIELD_INVALID","Auto reply field must be an email field",422);}
    const fieldIds=new Set(schema.fields.map(({definition})=>String(definition.id)));for(const policy of input.fieldPolicies??[])assertDomain(fieldIds.has(String(policy.fieldId)),"MAIL_FORM_FIELD_POLICY_INVALID","Field policy refers to a field outside the form table",422);
    const confirmationTtlSeconds=clamp(input.confirmationTtlSeconds??900,60,3600);const retentionDays=clamp(input.retentionDays??90,1,3650);
    const snapshot=await this.#cms.createMailForm(actor,{siteId:input.siteId,parentId:input.parentId,slug:input.slug,title:input.title,document:input.document??createEmptyDocument()});
    const now=this.#clock.now(); const definition:MailFormDefinition={id:asMailFormId(newId("mailForm")),workspaceId:site.workspaceId,siteId:site.id,contentItemId:snapshot.item.id,tableId:schema.table.id,recipientEmails:recipients,senderAddress:sender,subjectTemplate,autoReplyEnabled:Boolean(input.autoReplyEnabled),autoReplyEmailFieldKey:autoReplyKey,autoReplySubject,confirmationTtlSeconds,retentionDays,turnstileRequired:input.turnstileRequired??true,state:"active",createdAt:now,updatedAt:now};
    const requested=new Map((input.fieldPolicies??[]).map((p)=>[String(p.fieldId),p]));
    const policies:MailFormFieldPolicy[]=schema.fields.map(({definition:field})=>{const policy=requested.get(String(field.id));const privacyClass=policy?.privacyClass??defaultPrivacy(field.type);return{mailFormId:definition.id,fieldId:field.id,privacyClass,includeInOwnerNotification:policy?.includeInOwnerNotification??true,includeInAutoReply:policy?.includeInAutoReply??privacyClass!=="sensitive",createdAt:now};});
    await this.#store.createForm(definition,policies);await this.#audit(actor,definition,"mail-form.configure",Capabilities.MailFormManage,{tableId:definition.tableId,recipientCount:recipients.length,turnstileRequired:definition.turnstileRequired});return{definition,snapshot};
  }

  async prepareConfirmation(input:{mailFormId:MailFormId;values:Record<string,unknown>;turnstileToken?:string;remoteIp?:string;userAgent?:string;hostname?:string;honeypot?:string}):Promise<PreparedMailConfirmation>{
    const form=await this.#requirePublicForm(input.mailFormId);assertDomain(!input.honeypot,"MAIL_FORM_SPAM_REJECTED","Submission rejected",422);
    if(form.turnstileRequired){assertDomain(input.turnstileToken,"TURNSTILE_TOKEN_REQUIRED","Turnstile token is required",422);const result=await this.#bot.verify({token:input.turnstileToken,idempotencyKey:crypto.randomUUID(),...(input.remoteIp?{remoteIp:input.remoteIp}:{}),...(input.hostname?{expectedHostname:input.hostname}:{})});assertDomain(result.success,"TURNSTILE_VERIFICATION_FAILED","Turnstile verification failed",422,{errorCodes:result.errorCodes??[]});}
    const values=await this.#custom.validatePublicValues(form.tableId,input.values);assertMailPayloadLimits(values);const schema=await this.#custom.getTableSchema(form.tableId);const now=this.#clock.now();const valuesHash=await sha256(stableStringify({schemaVersion:schema.table.schemaVersion,values}));
    const session:MailConfirmationSession={id:asMailConfirmationId(newId("mailConfirmation")),mailFormId:form.id,schemaVersion:schema.table.schemaVersion,values,valuesHash,clientFingerprintHash:await this.#fingerprint(input.remoteIp,input.userAgent),expiresAt:now+form.confirmationTtlSeconds*1000,usedAt:null,createdAt:now};
    const token=await signCompactToken({confirmationId:session.id,mailFormId:form.id,valuesHash,exp:session.expiresAt},this.#signingSecret);await this.#store.createConfirmation(session);return{session,token};
  }

  async submitConfirmation(input:{confirmationId:MailConfirmationId;token:string}):Promise<MailSubmission>{
    const payload=await verifyCompactToken<{confirmationId:string;mailFormId:string;valuesHash:string;exp:number}>(input.token,this.#signingSecret);assertDomain(payload&&payload.confirmationId===input.confirmationId,"MAIL_CONFIRMATION_TOKEN_INVALID","Confirmation token is invalid",403);
    const session=await this.#store.getConfirmation(input.confirmationId);assertDomain(session,"MAIL_CONFIRMATION_NOT_FOUND","Confirmation not found",404);const now=this.#clock.now();assertDomain(payload.mailFormId===session.mailFormId&&payload.valuesHash===session.valuesHash&&payload.exp===session.expiresAt,"MAIL_CONFIRMATION_TOKEN_INVALID","Confirmation token does not match",403);assertDomain(session.expiresAt>=now,"MAIL_CONFIRMATION_EXPIRED","Confirmation has expired",410);assertDomain(session.usedAt===null,"MAIL_CONFIRMATION_USED","Confirmation has already been submitted",409);
    const form=await this.#requireForm(session.mailFormId);const schema=await this.#custom.getTableSchema(form.tableId);const currentHash=await sha256(stableStringify({schemaVersion:session.schemaVersion,values:session.values}));assertDomain(currentHash===session.valuesHash,"MAIL_CONFIRMATION_CORRUPT","Confirmation payload is corrupt",500);
    const submission:MailSubmission={id:asMailSubmissionId(newId("mailSubmission")),mailFormId:form.id,confirmationId:session.id,schemaVersion:session.schemaVersion,payloadHash:session.valuesHash,payloadState:"available",clientFingerprintHash:session.clientFingerprintHash,receivedAt:now,purgeAt:now+form.retentionDays*86400000,state:"notification-pending"};
    const storedPayload:MailSubmissionPayload={submissionId:submission.id,values:session.values,createdAt:now};const notifications=this.#buildNotifications(form,schema,submission,session.values,now);
    return this.#store.acceptSubmission({confirmationId:session.id,submission,payload:storedPayload,notifications,now});
  }

  async listSubmissions(actor:ActorContext,mailFormId:MailFormId):Promise<MailSubmissionView[]>{const form=await this.#requireForm(mailFormId);await this.#authorize(actor,form,Capabilities.MailSubmissionRead,"mail-submission.list","low");const policies=await this.#store.listFieldPolicies(form.id);const schema=await this.#custom.getTableSchema(form.tableId);return(await this.#store.listSubmissions(form.id)).map((v)=>this.#redact(v,schema,policies,false));}
  async getSubmission(actor:ActorContext,id:MailSubmissionId,input:{includeSensitive?:boolean}={}):Promise<MailSubmissionView>{const raw=await this.#store.getSubmission(id);assertDomain(raw,"MAIL_SUBMISSION_NOT_FOUND","Submission not found",404);const form=await this.#requireForm(raw.submission.mailFormId);await this.#authorize(actor,form,Capabilities.MailSubmissionRead,"mail-submission.read","low");let allowSensitive=false;if(input.includeSensitive&&actor.actorType==="human"){await this.#authorize(actor,form,Capabilities.MailSubmissionReadSensitive,"mail-submission.read-sensitive","high");allowSensitive=true;}const policies=await this.#store.listFieldPolicies(form.id);const schema=await this.#custom.getTableSchema(form.tableId);return this.#redact(raw,schema,policies,allowSensitive);}
  async purgeSubmission(actor:ActorContext,id:MailSubmissionId):Promise<MailSubmission>{const raw=await this.#store.getSubmission(id);assertDomain(raw,"MAIL_SUBMISSION_NOT_FOUND","Submission not found",404);const form=await this.#requireForm(raw.submission.mailFormId);await this.#authorize(actor,form,Capabilities.MailSubmissionPurge,"mail-submission.purge","high");const result=await this.#store.purgeSubmission(id,this.#clock.now());await this.#audit(actor,form,"mail-submission.purge",Capabilities.MailSubmissionPurge,{submissionId:id});return result;}
  async purgeExpired(actor:ActorContext,mailFormId:MailFormId):Promise<number>{const form=await this.#requireForm(mailFormId);await this.#authorize(actor,form,Capabilities.MailSubmissionPurge,"mail-submission.purge-expired","high");let count=0;for(const view of await this.#store.listSubmissions(form.id))if(view.submission.payloadState==="available"&&view.submission.purgeAt<=this.#clock.now()){await this.#store.purgeSubmission(view.submission.id,this.#clock.now());count++;}return count;}

  async deliverPending(actor:ActorContext,limit=20):Promise<MailNotificationDeliveryResult>{assertDomain(this.#sender,"MAIL_SENDER_NOT_CONFIGURED","Mail sender is not configured",503);const pending=await this.#store.listPendingNotifications(clamp(limit,1,100),this.#clock.now());let sent=0,failed=0;for(const notification of pending){const view=await this.#store.getSubmission(notification.submissionId);if(!view?.values){notification.state="failed";notification.attempts++;notification.lastError="Submission payload is unavailable";await this.#store.updateNotification(notification);failed++;continue;}const form=await this.#requireForm(view.submission.mailFormId);await this.#authorize(actor,form,Capabilities.MailNotificationDeliver,"mail-notification.deliver","high");const schema=await this.#custom.getTableSchema(form.tableId);const policies=await this.#store.listFieldPolicies(form.id);try{await this.#sender.send({to:notification.recipient,from:form.senderAddress,subject:notification.subject,text:renderMessage(schema,policies,view.values,notification.kind),...(notification.kind==="owner"&&form.autoReplyEmailFieldKey&&typeof view.values[form.autoReplyEmailFieldKey]==="string"?{replyTo:String(view.values[form.autoReplyEmailFieldKey])}:{})});notification.state="sent";notification.sentAt=this.#clock.now();notification.attempts++;notification.lastError="";await this.#store.updateNotification(notification);sent++;}catch(error){notification.attempts++;notification.lastError=error instanceof Error?error.message:String(error);notification.state=notification.attempts>=5?"failed":"pending";notification.availableAt=this.#clock.now()+Math.min(3600000,2**notification.attempts*30000);await this.#store.updateNotification(notification);failed++;}const all=await this.#store.listNotificationsForSubmission(notification.submissionId);if(all.some((n)=>n.state==="failed"))await this.#store.updateSubmissionState(notification.submissionId,"notification-failed");else if(all.length>0&&all.every((n)=>n.state==="sent"))await this.#store.updateSubmissionState(notification.submissionId,"notified");else await this.#store.updateSubmissionState(notification.submissionId,"notification-pending");}return{sent,failed};}

  async getFormByContentItem(contentItemId:import("@baser-edge/core-types").ContentItemId){return this.#store.getFormByContentItem(contentItemId);} async listForms(siteId:SiteId){return this.#store.listForms(siteId);} async getForm(id:MailFormId){return this.#requireForm(id);} async getSchema(id:MailFormId){const form=await this.#requireForm(id);return this.#custom.getTableSchema(form.tableId);}

  async #requirePublicForm(id:MailFormId){const form=await this.#requireForm(id);const snapshot=await this.#cms.store.getContentSnapshot(form.contentItemId);assertDomain(snapshot?.item.state==="active"&&snapshot.publishedRevision,"MAIL_FORM_NOT_PUBLISHED","Mail form is not published",404);return form;}
  async #requireForm(id:MailFormId){const form=await this.#store.getForm(id);assertDomain(form&&form.state==="active","MAIL_FORM_NOT_FOUND","Mail form not found",404);return form;}
  async #authorize(actor:ActorContext,form:MailFormDefinition,capability:string,action:string,risk:"low"|"high"){await this.#cms.authorizeOperation(actor,capability,{workspaceId:form.workspaceId,siteId:form.siteId,contentType:"mail-form",risk},action,"mail-form",form.id);}
  async #audit(actor:ActorContext,form:MailFormDefinition,action:string,capability:string,details:Record<string,unknown>){await this.#cms.recordSuccessfulOperation(actor,{workspaceId:form.workspaceId,siteId:form.siteId,action,resourceType:"mail-form",resourceId:form.id,revisionId:null,capability,details});}
  async #fingerprint(ip?:string,ua?:string){return sha256(`${this.#privacySalt}|${ip??""}|${ua??""}`);}
  #redact(view:MailSubmissionView,schema:CustomTableSchema,policies:MailFormFieldPolicy[],allowSensitive:boolean):MailSubmissionView{if(!view.values)return{...view,redacted:true};const byId=new Map(policies.map((p)=>[String(p.fieldId),p]));const values:Record<string,unknown>={};for(const {definition} of schema.fields){const policy=byId.get(String(definition.id));const value=view.values[definition.key];values[definition.key]=allowSensitive||policy?.privacyClass==="non-personal"?value:redactedValue(value,policy?.privacyClass??"personal");}return{...view,values,redacted:!allowSensitive};}
  #buildNotifications(form:MailFormDefinition,schema:CustomTableSchema,submission:MailSubmission,values:Record<string,unknown>,now:number):MailNotification[]{const title=String(schema.table.name);const ownerSubject=safeOutboundSubject(form.subjectTemplate.replace(/\{\{formTitle\}\}/g,title));const list:MailNotification[]=form.recipientEmails.map((recipient)=>({id:asMailNotificationId(newId("mailNotification")),submissionId:submission.id,kind:"owner",recipient,subject:ownerSubject,state:"pending",attempts:0,availableAt:now,sentAt:null,lastError:""}));if(form.autoReplyEnabled&&form.autoReplyEmailFieldKey){const recipient=values[form.autoReplyEmailFieldKey];if(typeof recipient==="string")list.push({id:asMailNotificationId(newId("mailNotification")),submissionId:submission.id,kind:"auto-reply",recipient,subject:safeOutboundSubject(form.autoReplySubject),state:"pending",attempts:0,availableAt:now,sentAt:null,lastError:""});}return list;}
}

function renderMessage(schema:CustomTableSchema,policies:MailFormFieldPolicy[],values:Record<string,unknown>,kind:"owner"|"auto-reply"):string{const policyByField=new Map(policies.map((p)=>[String(p.fieldId),p]));const lines=[kind==="owner"?"フォームから送信がありました。":"お問い合わせを受け付けました。","",...schema.fields.filter(({definition})=>{const p=policyByField.get(String(definition.id));return kind==="owner"?p?.includeInOwnerNotification:p?.includeInAutoReply;}).map(({definition,relation})=>`${relation.labelOverride??definition.name}: ${formatValue(values[definition.key])}`)];return lines.join("\n");}
function formatValue(v:unknown):string{if(v===null||v===undefined)return"";return Array.isArray(v)?v.join(", "):String(v);}
function normalizeEmail(value:string,label:string){const email=value.trim().toLowerCase();assertDomain(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),"MAIL_EMAIL_INVALID",`${label} must be an email address`,422);return email;}
function normalizeEmails(values:string[]){const result=[...new Set(values.map((v)=>normalizeEmail(v,"recipientEmails")))];assertDomain(result.length>0&&result.length<=20,"MAIL_RECIPIENTS_INVALID","One to twenty recipients are required",422);return result;}
function normalizeSubject(value:string,label:string):string{const subject=value.trim();assertDomain(subject.length>0&&subject.length<=200&&!/[\r\n]/.test(subject),"MAIL_SUBJECT_INVALID",`${label} must be a single line of at most 200 characters`,422);return subject;}
function safeOutboundSubject(value:string):string{return value.replace(/[\r\n]+/g," ").trim().slice(0,200)||"Notification";}
function redactedValue(value:unknown,privacy:PrivacyClass):unknown{if(value===null||value===undefined)return value;if(privacy==="sensitive")return"[sensitive]";if(typeof value==="string"){if(value.includes("@")){const [local,domain]=value.split("@");return `${local?.slice(0,1)??"*"}***@${domain??"***"}`;}return value.length<=2?"**":`${value.slice(0,1)}***${value.slice(-1)}`;}return"[personal]";}
function defaultPrivacy(type:string):PrivacyClass{return type==="email"||type==="tel"?"personal":"non-personal";}
function assertMailPayloadLimits(values:Record<string,unknown>):void{const encoder=new TextEncoder();assertDomain(encoder.encode(stableStringify(values)).byteLength<=262144,"MAIL_FORM_PAYLOAD_TOO_LARGE","Form payload is too large",413);for(const value of Object.values(values)){if(typeof value==="string")assertDomain(encoder.encode(value).byteLength<=65536,"MAIL_FORM_FIELD_TOO_LARGE","A form field is too large",413);if(Array.isArray(value))assertDomain(value.length<=100,"MAIL_FORM_FIELD_TOO_LARGE","A multi-value field contains too many values",413);}}
function clamp(v:number,min:number,max:number){return Math.min(max,Math.max(min,Math.trunc(v)));}
